services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - ./runtime/pg-data:/var/lib/postgresql/data:rw
